server:
  port: 8080

spring:
  application:
    name: customerKata

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    platform: h2

  h2:
    console:
      enabled: true
